### ISSUE TITLE
mCubeRenderer doesn't initionalized in some cases

### ISSUE THREAD

**Issue by breakJeff** [googlecast/CastRemoteDisplay-android#10]
Download latest code from github, throw following NPE even connection is established.

ava.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.castremotedisplay.CubeRenderer.changeColor()' on a null object reference
                                                                                   at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
                                                                                   at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
                                                                                   at android.view.View.performClick(View.java:5204)
                                                                                   at android.view.View$PerformClick.run(View.java:21153)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sonaarya** [comment]
com.example.castremotedisplay E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.example.castremotedisplay, PID: 18635
                                                                               java.lang.NullPointerException
                                                                                   at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
                                                                                   at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
                                                                                   at android.view.View.performClick(View.java:4651)
                                                                                   at android.view.View$PerformClick.run(View.java:19310)
                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:146)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5653)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by nischithakv** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.castremotedisplay.CubeRenderer.changeColor()' on a null object reference
                                                                                   at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
                                                                                   at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
                                                                                   at android.view.View.performClick(View.java:5207)
                                                                                   at android.view.View$PerformClick.run(View.java:21168)
                                                                                   at android.os.Handler.handleCallback(Handler.java:746)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by ingsaurabh** [comment]
Same here, anybody here Issue reported on 29 dec 2015 but no one here from google to discuss it

```
Process: com.example.castremotedisplay, PID: 28775
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.castremotedisplay.CubeRenderer.changeColor()' on a null object reference
   at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
   at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
   at android.view.View.performClick(View.java:4785)
   at android.view.View$PerformClick.run(View.java:19884)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5343)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by nischithakv** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.castremotedisplay.CubeRenderer.changeColor()' on a null object reference
at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
at android.view.View.performClick(View.java:5207)
at android.view.View$PerformClick.run(View.java:21168)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by nischithakv** [comment]
PresentationService class  add  mCubeRenderer= new CubeRenderer(); this line .

**Comment by nmr8acme** [comment]
Seems to be some kind of race condition, if I run with a debugger attached and a few breakpoints enabled then it works fine.

**Comment by no-body** [comment]
Any clue another year later ?
I'm trying to mirror my app on a tv equipped with a chromecast, but I dont find a way.. Any idea ?
thanks

**Comment by entertailion** [comment]
You can file a bug against the Cast SDK: https://issuetracker.google.com/issues?q=componentid:190205%20status:open&s=modified_time:desc
