### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nischithakv** [googlecast/CastRemoteDisplay-android#15]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.castremotedisplay.CubeRenderer.changeColor()' on a null object reference
at com.example.castremotedisplay.PresentationService.changeColor(PresentationService.java:92)
at com.example.castremotedisplay.CastRemoteDisplayActivity$1.onClick(CastRemoteDisplayActivity.java:93)
at android.view.View.performClick(View.java:5207)
at android.view.View$PerformClick.run(View.java:21168)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by entertailion** [comment]
Cannot reproduce this error. Make sure you have the latest version of the Android SDK and the latest Google Play services installed on your device.

**Comment by nischithakv** [comment]
i installed latest Android SDk and Play service i am getting same issue

**Comment by nischithakv** [comment]
This is null pointer exception

**Comment by entertailion** [comment]
What mobile device are you using and what version of Android is it running?

**Comment by nischithakv** [comment]
i have used own application ID . Moto G (3rd generation)and Smasung S7 . Android Version 6.0.1 both devices

**Comment by nischithakv** [comment]
This below line i am getting error .
                    presentationService.changeColor();

**Comment by nischithakv** [comment]
issues got solved
